### ISSUE TITLE
Method  io.jsonwebtoken.Jwts.parserBuilder() not found after migrating to 0.11.2

### ISSUE THREAD

**Issue by ckmoga** [jwtk/jjwt#638]
I have just migrated to the latest version and started getting this error at runtime:

`java.lang.NoSuchMethodError: io.jsonwebtoken.Jwts.parserBuilder()`

My dependencies:

```gradle
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.1'
	implementation group: 'com.kastkode', name: 'springsandwich', version: '1.0.2'
	implementation('org.springframework.boot:spring-boot-starter-tomcat')
	implementation('org.codehaus.groovy:groovy-all:3.0.7')
	implementation "io.jsonwebtoken:jjwt-api:0.11.2"
	runtimeOnly "io.jsonwebtoken:jjwt-jackson:0.11.2",
			       "io.jsonwebtoken:jjwt-impl:0.11.2",
			       "org.bouncycastle:bcprov-jdk15on:1.68"
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

**Comment by lhazlewood** [comment]
What version did you use previously?  Were you able to come to a resolution?

**Comment by ckmoga** [comment]
I was on 0.10.2 but my issue was related to the fact that the dependency was runtimeOnly. My project is an SSO library that consumers import and utiliize for authentication. After adding the same dependencies to consumers the issue was resolved.

**Comment by lhazlewood** [comment]
Thanks for the clarification!

**Comment by indrajeet125** [comment]
use only` Jwts.parser()` this works for me

**Comment by SohamBagde** [comment]
> use only` Jwts.parser()` this works for me

this worked!

**Comment by MuradSharifzada** [comment]
i used only Jwts.parser()  this method works for me
